# -*- coding: utf-8 -*-
"""news_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jPZuV4bm3FF7nN5PaoLCVBpVz6r3CYd

# 📰 Task 1: News Topic Classifier Using BERT

**Objective:** Fine-tune `bert-base-uncased` on the AG News Dataset to classify news headlines into 4 categories:
- 0 → World
- 1 → Sports
- 2 → Business
- 3 → Sci/Tech

---

## 📦 Step 1 — Install Dependencies
"""

# DO NOT reinstall torch or torchvision — Colab's preinstalled pair is already
# matched to its GPU/CUDA build. Reinstalling either one breaks the ABI match
# between them (RuntimeError: operator torchvision::nms does not exist).
# We only pin transformers/accelerate to versions compatible with Colab's torch.
!pip install -U datasets huggingface_hub fsspec "transformers==4.44.2" "accelerate==0.34.2" scikit-learn gradio -q
# IMPORTANT: after this finishes, go to Runtime -> Restart session,
# then re-run ALL cells from the top in this exact freshly-restarted session.

"""## 📥 Step 2 — Load AG News Dataset"""

from datasets import load_dataset

dataset = load_dataset('fancyzhx/ag_news')
print(dataset)
print('\nSample entry:')
print(dataset['train'][0])

"""## 🔍 Step 3 — Explore the Dataset"""

import pandas as pd

LABEL_NAMES = ['World', 'Sports', 'Business', 'Sci/Tech']

# Convert to pandas for easy exploration
train_df = pd.DataFrame(dataset['train'])
train_df['category'] = train_df['label'].map(lambda x: LABEL_NAMES[x])

print('Dataset shape:', train_df.shape)
print('\nClass distribution:')
print(train_df['category'].value_counts())

train_df[['text', 'category']].head(10)

"""## ✂️ Step 4 — Tokenize with BERT Tokenizer"""

from transformers import BertTokenizer

MODEL_NAME = 'bert-base-uncased'
MAX_LEN = 128

tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)

# Demo tokenization on one sample
sample = dataset['train'][0]['text']
tokens = tokenizer(sample, max_length=MAX_LEN, truncation=True, padding='max_length')
print('Text     :', sample[:100], '...')
print('Input IDs:', tokens['input_ids'][:20], '...')
print('Tokens   :', tokenizer.convert_ids_to_tokens(tokens['input_ids'][:20]))

# Use a subset for faster training in notebook (increase for full run)
train_dataset = dataset['train'].shuffle(seed=42).select(range(8000))
test_dataset  = dataset['test'].shuffle(seed=42).select(range(2000))

def tokenize(batch):
    return tokenizer(batch['text'], padding='max_length', truncation=True, max_length=MAX_LEN)

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset  = test_dataset.map(tokenize, batched=True)

train_dataset = train_dataset.rename_column('label', 'labels')
test_dataset  = test_dataset.rename_column('label', 'labels')

train_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format('torch',  columns=['input_ids', 'attention_mask', 'labels'])

print('Train size:', len(train_dataset))
print('Test size :', len(test_dataset))

"""## 🤖 Step 5 — Load BERT & Fine-tune"""

import numpy as np
from transformers import BertForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, f1_score

model = BertForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=4)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, predictions)
    f1  = f1_score(labels, predictions, average='weighted')
    return {'accuracy': acc, 'f1': f1}

training_args = TrainingArguments(
    output_dir='./bert_ag_news',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1',
    logging_steps=50,
    report_to='none',
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

trainer.train()

"""## 📊 Step 6 — Evaluate Model"""

results = trainer.evaluate()
print(f"\n=== FINAL EVALUATION ===")
print(f"Accuracy : {results['eval_accuracy']:.4f}")
print(f"F1-Score : {results['eval_f1']:.4f}")

# Detailed classification report
from sklearn.metrics import classification_report
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
model.eval()

all_preds, all_labels = [], []

from torch.utils.data import DataLoader
loader = DataLoader(test_dataset, batch_size=32)

with torch.no_grad():
    for batch in loader:
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels         = batch['labels']
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        preds   = torch.argmax(outputs.logits, dim=-1).cpu().numpy()
        all_preds.extend(preds)
        all_labels.extend(labels.numpy())

print(classification_report(all_labels, all_preds, target_names=LABEL_NAMES))

"""## 💾 Step 7 — Save Model"""

model.save_pretrained('./bert_ag_news')
tokenizer.save_pretrained('./bert_ag_news')
print('Model and tokenizer saved to ./bert_ag_news/')

"""## 🚀 Step 8 — Gradio Live Demo"""

import gradio as gr
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
model.eval()

def predict(text: str):
    if not text.strip():
        return 'Please enter a headline.'
    inputs = tokenizer(
        text, return_tensors='pt',
        padding=True, truncation=True, max_length=128
    ).to(device)
    with torch.no_grad():
        logits = model(**inputs).logits
    probs = torch.softmax(logits, dim=-1)[0].cpu().numpy()
    return {LABEL_NAMES[i]: float(probs[i]) for i in range(4)}

gr.Interface(
    fn=predict,
    inputs=gr.Textbox(lines=2, placeholder='Enter a news headline...', label='Headline'),
    outputs=gr.Label(num_top_classes=4, label='Category Probabilities'),
    title='📰 News Topic Classifier (BERT)',
    description='Fine-tuned bert-base-uncased on AG News | World · Sports · Business · Sci/Tech',
    examples=[
        ['NASA launches new Mars rover to search for ancient life'],
        ['Stock markets surge as inflation drops to 2-year low'],
        ['Real Madrid wins Champions League final in extra time'],
        ['New AI chip from NVIDIA claims 10x speed over H100'],
    ]
).launch()

model.save_pretrained('/content/drive/MyDrive/bert_ag_news')  # if Drive is mounted
tokenizer.save_pretrained('/content/drive/MyDrive/bert_ag_news')